# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
       node-version: 18
    - name: install pnpm
      run: |
        npm install pnpm -g
        
    - name: install rsync
      run: |
        sudo apt-get update && sudo apt-get -y install rsync       

    - name: build front-end
      working-directory: ./
      run: |
        mkdir font-end
        cp package.json ./font-end
        cp pnpm-lock.yaml ./font-end
        rsync -av --exclude 'font-end' * font-end/
        cd font-end
        pnpm install
        pnpm run build

    - name: build backend
      working-directory: ./
      run: |
        mkdir backend
        cp -r service/* backend/
        cd backend
        pnpm install --no-frozen-lockfile
        pnpm run build
        
    - name: pack build result
      working-directory: ./
      run: |
        mkdir pack
        cp service/package.json pack/
        cp service/pnpm-lock.yaml pack/
        cd pack
        pnpm install --production --no-frozen-lockfile
        cd ..
        cp -r service/* pack/
        cp -r font-end/dist/ pack/public
        cp -r backend/build/ pack/build
  
#    - name: Archive production artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: service-artifact
#        path: |
#          pack
          
    - name: Copy file to server via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.PORT }}
         source: pack/*
         target: www/html/chatgpt
