# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
       node-version: 18
    - name: install pnpm
      run: |
        npm install pnpm -g

    - name: build web
      working-directory: ./
      run: |
        pnpm install
        pnpm run build

    - name: build server
      working-directory: ./service
      run: |
        pnpm install --no-frozen-lockfile
        pnpm run build
        
    - name: pack
      working-directory: ./service
      run: |
        pnpm install --production
        cp -r ${{ github.workspace }}/dist/ ${{ github.workspace }}/service/public
  
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: service-artifact
        path: |
          service
